# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 884c423bc5788a470bb0da290c4a9eae7a2910377f6e7e52b59826f24cb7ea2a2b243d48e085596ab6cf8fc99c3927f6835442e710cab7ced7497f07f2575b6e

test:
  secret_key_base: f9a960f20192d63d985394ef26d757663aa74865644af6ffddc53b9f58fe710a4ae649a6e0b30ff6c30f51e80390d61553d9ea5253700ce86ab266e716555756

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
